var annotated_dup =
[
    [ "ArbolBinario", "class_arbol_binario.html", null ],
    [ "AscendingBinaryTreeListTrait", "struct_ascending_binary_tree_list_trait.html", null ],
    [ "AscendingDoubleLinkedListTrait", "struct_ascending_double_linked_list_trait.html", null ],
    [ "AscendingHeapTrait", "struct_ascending_heap_trait.html", null ],
    [ "AscendingLinkedListTrait", "struct_ascending_linked_list_trait.html", null ],
    [ "AscendingTrait", "struct_ascending_trait.html", null ],
    [ "BaseBinaryTreeListTrait", "struct_base_binary_tree_list_trait.html", null ],
    [ "BaseContainerTrait", "struct_base_container_trait.html", null ],
    [ "BaseDoubleLinkedListTrait", "struct_base_double_linked_list_trait.html", null ],
    [ "BaseLinkedListTrait", "struct_base_linked_list_trait.html", null ],
    [ "BinaryTree", "class_binary_tree.html", null ],
    [ "BinaryTreeBackwardInorderIterator", "class_binary_tree_backward_inorder_iterator.html", null ],
    [ "BinaryTreeForwardInorderIterator", "class_binary_tree_forward_inorder_iterator.html", null ],
    [ "BinaryTreeNode", "class_binary_tree_node.html", null ],
    [ "BTree", "class_b_tree.html", null ],
    [ "BTreeBackwardIterator", "class_b_tree_backward_iterator.html", null ],
    [ "BTreeForwardIterator", "class_b_tree_forward_iterator.html", null ],
    [ "CBTreePage", "class_c_b_tree_page.html", null ],
    [ "DescendingBinaryTreeListTrait", "struct_descending_binary_tree_list_trait.html", null ],
    [ "DescendingDoubleLinkedListTrait", "struct_descending_double_linked_list_trait.html", null ],
    [ "DescendingHeapTrait", "struct_descending_heap_trait.html", null ],
    [ "DescendingLinkedListTrait", "struct_descending_linked_list_trait.html", null ],
    [ "DescendingTrait", "struct_descending_trait.html", null ],
    [ "DLLNode", "class_d_l_l_node.html", null ],
    [ "DoubleLinkedListBackwardIterator", "class_double_linked_list_backward_iterator.html", null ],
    [ "general_iterator", "classgeneral__iterator.html", null ],
    [ "Heap", "class_heap.html", null ],
    [ "HeapNode", "class_heap_node.html", null ],
    [ "LinkedList", "class_linked_list.html", null ],
    [ "LinkedList&lt; Traits &gt;", "class_linked_list_3_01_traits_01_4.html", null ],
    [ "LinkedListForwardIterator", "class_linked_list_forward_iterator.html", null ],
    [ "LLNode", "class_l_l_node.html", null ],
    [ "Nodo", "struct_nodo.html", null ],
    [ "tagNode", "structtag_node.html", null ],
    [ "Vector", "class_vector.html", null ],
    [ "vector_backward_iterator", "classvector__backward__iterator.html", null ],
    [ "vector_forward_iterator", "classvector__forward__iterator.html", null ],
    [ "VectorNode", "struct_vector_node.html", null ],
    [ "VectorTraits", "struct_vector_traits.html", null ]
];